import { Anton, Lexend, Roboto } from "next/font/google";
import "./globals.css";

import Navbar from "./components/navbar";
import Footer from "./components/footer";
import AppProvider from "./providers";

// const inter = Inter({ subsets: ["latin"] });
const Rob = Roboto({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-roboto",
});
const Ant = Anton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton",
});

const Lex = Lexend({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lexend",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${Rob.variable}  ${Lex.variable}`}>
      <AppProvider>
        <body className={Lex.className}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </AppProvider>
    </html>
  );
}
